### ISSUE TITLE
Opensuse leap 15.5, Xstream 

### ISSUE THREAD

**Issue by Enniomon** [streamxstream/plugin.video.xstream#168]
**Beschreibe den Fehler**
Keine update meldung von xstream oder urlresolver oben recht, wenn kodi startet

**Erwartetes Verhalten**
wenn kodi startet soll oben rechts die meldung erscheinen ob xstream wurde updated oder es gibt kein update. Das selbe fuer urlresolver

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [z.B. Nvidia Shield, Android TV 11]
 - Kodi Version: [z.B. Kodi 20]
 - Xstream Version: [z.B. 4.0.8~nightly1]
 - Resolver Version: [z.B. 5.1.8.9]

**Zusätzliche Informationen**
Füge zusätzliche/ergänzende Informationen zum Fehler hinzu

Nach einem system update, Xstream nicht mehr faehig urlresolver oder xstream-update durchzufuehern und von version 4.0.8 zu 4.0.7 zurueck versetzt worden, statdessen kommt eine error meldung zum Vorschein. 
Im kodi.log sehe ich diese Zeilen: 

2023-12-03 18:38:45.330 T:9294    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: future feature annotations is not defined (__init__.py, line 5)
                                                   Traceback (most recent call last):
                                                     File "../.kodi/addons/plugin.video.xstream/service.py", line 18, in <module>
                                                       from resources.lib import updateManager
                                                     File "../.kodi/addons/plugin.video.xstream/resources/lib/updateManager.py", line 9, in <module>
                                                       import requests
                                                     File "../.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "../.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
                                                       from __future__ import annotations
                                                                                        ^
                                                   SyntaxError: future feature annotations is not defined
                                                   -->End of Python script error report<--

**Comment by Heptamer** [comment]
Lass mich raten, du hast auf KODi 21 aktualisiert?

**Comment by Heptamer** [comment]
Hier tut sich auch nichts mehr -> closed
