### ISSUE TITLE
Fehler Dokus4

### ISSUE THREAD

**Issue by polojoe** [streamxstream/plugin.video.xstream#40]
Ich bekomme bei Doku4 immer folgenden Fehler
020-08-26 17:44:43.009 T:2863047536  NOTICE: 	[xStream] -> dokus4: *---- Running xStream, version 3.5.17~nightly ----*
2020-08-26 17:44:43.010 T:2863047536  NOTICE: 	[xStream] -> dokus4: Python-Version: 2.7.16
2020-08-26 17:44:43.010 T:2863047536  NOTICE: 	[xStream] -> dokus4: {'function': 'load', 'params': '0', 'site': 'dokus4', 'title': 'Dokus4'}
2020-08-26 17:44:43.010 T:2863047536  NOTICE: 	[xStream] -> dokus4: Call function 'load' from 'dokus4'
2020-08-26 17:44:43.059 T:2863047536  NOTICE: 	[xStream] -> dokus4: Load Dokus4
2020-08-26 17:44:44.698 T:2443592560  NOTICE: 	[xStream] -> dokus4: *---- Running xStream, version 3.5.17~nightly ----*
2020-08-26 17:44:44.698 T:2443592560  NOTICE: 	[xStream] -> dokus4: Python-Version: 2.7.16
2020-08-26 17:44:44.698 T:2443592560  NOTICE: 	[xStream] -> dokus4: {'function': 'showEntries', 'sUrl': 'http://www.dokus4.me/', 'site': 'dokus4', 'title': 'Dokus'}
2020-08-26 17:44:44.699 T:2443592560  NOTICE: 	[xStream] -> dokus4: Call function 'showEntries' from 'dokus4'
2020-08-26 17:44:48.562 T:2863047536  NOTICE: 	[xStream] -> dokus4: *---- Running xStream, version 3.5.17~nightly ----*
2020-08-26 17:44:48.562 T:2863047536  NOTICE: 	[xStream] -> dokus4: Python-Version: 2.7.16
2020-08-26 17:44:48.562 T:2863047536  NOTICE: 	[xStream] -> dokus4: {'function': 'getHosterUrl', 'thumb': 'http://www.dokus4.me/wp-content/uploads/2020/08/Borstenviecher-die-Nordstory.png', 'title': 'Borstenviecher - Vom Gl\xc3\xbcck, Schwein zu haben', 'url': 'http://www.dokus4.me/index.php/2020/08/14/borstenviecher-vom-glueck-schwein-zu-haben', 'sUrl': 'http://www.dokus4.me/', 'site': 'dokus4', 'playMode': 'play', 'MovieTitle': 'Borstenviecher - Vom Gl\xc3\xbcck, Schwein zu haben'}
2020-08-26 17:44:48.592 T:2863047536  NOTICE: 	[xStream] -> dokus4: auto stream initiated
2020-08-26 17:44:48.663 T:2863047536   ERROR: 	[xStream] -> dokus4: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.xstream/default.py", line 20, in <module>
                                                run()
                                              File "/storage/.kodi/addons/plugin.video.xstream/xstream.py", line 12, in run
                                                parseUrl()
                                              File "/storage/.kodi/addons/plugin.video.xstream/xstream.py", line 204, in parseUrl
                                                cHosterGui().streamAuto(playMode, sSiteName, sFunction)
                                              File "/storage/.kodi/addons/plugin.video.xstream/resources/lib/gui/hoster.py", line 286, in streamAuto
                                                siteResult = function()
                                              File "/storage/.kodi/addons/plugin.video.xstream/sites/dokus4.py", line 70, in getHosterUrl
                                                sHtmlContent = cRequestHandler(sUrl).request()
                                              File "/storage/.kodi/addons/plugin.video.xstream/resources/lib/handler/requestHandler.py", line 77, in request
                                                self.__sUrl = self.__sUrl.replace(' ', '+')
                                            AttributeError: 'bool' object has no attribute 'replace'
2020-08-26 17:45:05.544 T:3011990864   ERROR: Playlist Player: skipping unplayable item: 0, path

**Comment by anis3** [comment]
hallo polojoe

danke für den hinweis
ich habe das problem gefixt

muss dich darauf **hinweißen** das es mit
**hosterauswahl automatisch bei mehreren seiten
probleme** gibt die ich nicht so einfach lösen kann
ich arbeite an den problem wird vermutlich aber
längere zeit in anspruch nehmen da ich die funktion
**komplett überdenken/überarbeiten** muss

problemseiten hosterauswahl automatisch:
hdfilme
kinoger
topstreamfilm

aktuell kann ich nur empfehlen
**hosterauswahl Dialog**
zu benutzen

LG Anis
